# Generated by Django 2.2.1 on 2019-09-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginuser',
            table='LoginUser',
        ),
    ]
