# Generated by Django 2.2.1 on 2019-09-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0002_auto_20190919_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginuser',
            old_name='user',
            new_name='username',
        ),
    ]
