# Generated by Django 2.2.1 on 2019-09-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0004_doods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doods',
            new_name='Goods',
        ),
    ]
