# Generated by Django 2.2.1 on 2019-09-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0005_auto_20190920_1716'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='Goods',
        ),
    ]
